# Generated by Django 4.1.2 on 2022-11-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("course_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("dept_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "instructor_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("instructor_name", models.CharField(max_length=50)),
                ("mobile", models.IntegerField()),
                ("department", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("mail", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("std_name", models.CharField(max_length=50)),
                ("photo", models.CharField(max_length=1500)),
                ("department", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=15)),
                ("mail", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Teaches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_students", models.IntegerField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Student.course"
                    ),
                ),
                (
                    "instructor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.instructor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Takes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=5)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Student.course"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("status", models.BooleanField()),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Student.course"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Student.department"
            ),
        ),
    ]
