# Generated by Django 4.1.2 on 2022-11-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="course", table="course",),
        migrations.AlterModelTable(name="dailyattendance", table="dailyattendance",),
        migrations.AlterModelTable(name="department", table="department",),
        migrations.AlterModelTable(name="instructor", table="instructor",),
        migrations.AlterModelTable(name="student", table="student",),
        migrations.AlterModelTable(name="takes", table="takes",),
        migrations.AlterModelTable(name="teaches", table="teaches",),
    ]
