# Generated by Django 4.1.2 on 2022-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0003_remove_instructor_instructor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
    ]
