# Generated by Django 4.1.2 on 2022-11-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0004_alter_instructor_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teaches", old_name="instructor_id", new_name="mail",
        ),
    ]
