# Generated by Django 4.1.2 on 2022-11-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0007_alter_teaches_num_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="takes",
            name="attendace_percentage",
            field=models.DecimalField(decimal_places=0, default=100, max_digits=3),
        ),
    ]
