# Generated by Django 4.1.2 on 2022-11-19 14:46

import Student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0009_alter_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="faceEncoding",
            field=models.FileField(default=None, null=True, upload_to="encodings"),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                default="", null=True, upload_to=Student.models.get_file_path
            ),
        ),
    ]
