# Generated by Django 4.1.2 on 2022-11-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0010_student_faceencoding_alter_student_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="faceEncoding",),
    ]
