# Generated by Django 4.1.2 on 2022-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0011_remove_student_faceencoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="faceEncoding",
            field=models.FileField(default="", null=True, upload_to="encodings/"),
        ),
    ]
