# Generated by Django 4.2.3 on 2023-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_remove_student_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
